[build-system]
build-backend = "hatchling.build"
requires = [
    "hatchling",
]

[project]
name = "aa-hrapps"
description = "A recruitment tool for allianceauth"
readme = "README.md"
keywords = [
    "allianceauth",
    "eveonline",
    "recruitment",
    "hr",
    "human resources",
]
license = { file = "LICENSE" }
authors = [
    { name = "Col Crunch", email = "colcrunch@fancypants.space" },
]
requires-python = ">=3.10"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dynamic = [
    "version",
]
dependencies = [
    "allianceauth>=4",
    "pillow>=12.3.0"
]

optional-dependencies.discordbot = [
    "allianceauth-discordbot>=5",
]
urls.Documentation = "https://github.com/colcrunch/aa-hrapps/blob/master/README.md"
urls.Homepage = "https://github.com/colcrunch/aa-hrapps"
urls.Source = "https://github.com/colcrunch/aa-hrapps.git"
urls.Tracker = "https://github.com/colcrunch/aa-hrapps/-/issues"

[tool.hatch.build]
include = [
    "/hrapps",
]

[tool.hatch.version]
path = "hrapps/__init__.py"

[tool.pycodestyle]
max-line-length = 121
