# Generated by Django 4.2.26 on 2025-11-30 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRAppPerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_hrapps', 'Can access hrapps.'), ('manage_hrapps', 'Full management access.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eveonline.evecorporationinfo')),
            ],
            options={
                'permissions': (('manage_all_forms', 'Can manage forms.'), ('create_forms', 'Can create forms.'), ('manage_corp_forms', 'Can manage corp forms.')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responses', to='hrapps.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_all_responses', 'Can view responses.'), ('create_response', 'Can create responses.'), ('view_corp_responses', 'Can view corp responses.')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ResponseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='hrapps.responsecomment')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hrapps.formresponse')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('create_comment', 'Can comment on form responses.'), ('view_comment', 'Can view comments on form responses.')),
                'default_permissions': (),
            },
        ),
    ]
