# Generated by Django 5.2.14 on 2026-08-13 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0026_alter_characterownership_user_and_more'),
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRAppPerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_hrapps', 'Can access hrapps.'), ('access_hradmin', 'Can access the admin frontend.'), ('manage_hrapps', 'Full management access.')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='hrapps.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eveonline.evecorporationinfo')),
            ],
            options={
                'permissions': (('manage_all_forms', 'Can manage forms.'), ('create_forms', 'Can create forms.'), ('manage_corp_forms', 'Can manage corp forms.')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('response', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=15)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responses', to='hrapps.form')),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruited_responses', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_all_responses', 'Can view responses.'), ('create_response', 'Can create responses.'), ('view_corp_responses', 'Can view corp responses.'), ('claim_recruiter', 'Can claim a response as a recruiter.'), ('claim_reviewer', 'Can claim a response as a reviewer.'), ('modify_status', 'Can change the status of a response.')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='hrapps/attachments/')),
                ('question_id', models.IntegerField(blank=True, null=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hrapps.formresponse')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HRAppDiscordSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_welcome_messages', models.BooleanField(default=False)),
                ('welcome_channel', models.BigIntegerField(blank=True, null=True)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('use_recruitment_threads', models.BooleanField(default=False)),
                ('recruitment_thread_channel', models.BigIntegerField(blank=True, null=True)),
                ('recruiter_role', models.BigIntegerField(blank=True, null=True)),
                ('recruit_role', models.BigIntegerField(blank=True, null=True)),
                ('enable_application_notifications', models.BooleanField(default=False)),
                ('application_notification_channel', models.BigIntegerField(blank=True, null=True)),
                ('ignored_states', models.ManyToManyField(blank=True, to='authentication.state')),
            ],
            options={
                'verbose_name': 'HRApp Discord Settings',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ResponseComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hrapps.comment')),
                ('private', models.BooleanField(default=False)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hrapps.formresponse')),
            ],
            options={
                'permissions': (('create_comment', 'Can comment on form responses.'), ('view_comment', 'Can view comments on form responses.')),
                'default_permissions': (),
            },
            bases=('hrapps.comment',),
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('corporation', 'active'), name='only_one_active_form_per_corp'),
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(fields=('corporation', 'name'), name='unique_form_name_per_corp'),
        ),
        migrations.AddConstraint(
            model_name='hrappdiscordsettings',
            constraint=models.CheckConstraint(condition=models.Q(('use_recruitment_threads', False), ('recruitment_thread_channel__isnull', False), _connector='OR'), name='recruitment_thread_channel_required_if_threads_enabled'),
        ),
        migrations.AddConstraint(
            model_name='hrappdiscordsettings',
            constraint=models.CheckConstraint(condition=models.Q(('enable_welcome_messages', False), ('welcome_channel__isnull', False), _connector='OR'), name='welcome_channel_required_if_welcome_messages_enabled'),
        ),
    ]
