# Generated by Django 4.2.11 on 2026-02-17 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
