# Generated by Django 5.2.14 on 2026-08-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'default_permissions': (), 'permissions': (('view_admin_attachments', 'Can view admin attachments on form responses.'), ('upload_admin_attachments', 'Can upload admin attachments on form responses.'))},
        ),
    ]
