# Generated by Django 4.2.11 on 2026-01-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapps', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('corporation', 'active'), name='only_one_active_form_per_corp'),
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(fields=('corporation', 'name'), name='unique_form_name_per_corp'),
        ),
    ]
