# Generated by Django 4.2.20 on 2026-03-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapps', '0002_formresponse_reviewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formresponse',
            options={'default_permissions': (), 'permissions': (('view_all_responses', 'Can view responses.'), ('create_response', 'Can create responses.'), ('view_corp_responses', 'Can view corp responses.'), ('claim_recruiter', 'Can claim a response as a recruiter.'), ('claim_reviewer', 'Can claim a response as a reviewer.'))},
        ),
    ]
