# Generated by Django 4.2.20 on 2026-03-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapps', '0003_alter_formresponse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formresponse',
            options={'default_permissions': (), 'permissions': (('view_all_responses', 'Can view responses.'), ('create_response', 'Can create responses.'), ('view_corp_responses', 'Can view corp responses.'), ('claim_recruiter', 'Can claim a response as a recruiter.'), ('claim_reviewer', 'Can claim a response as a reviewer.'), ('modify_status', 'Can change the status of a response.'))},
        ),
        migrations.AlterModelOptions(
            name='hrappperms',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_hrapps', 'Can access hrapps.'), ('access_hradmin', 'Can access the admin frontend.'), ('manage_hrapps', 'Full management access.'))},
        ),
    ]
