# Generated by Django 5.2.14 on 2026-05-27 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapps', '0004_alter_formresponse_options_alter_hrappperms_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
