# Generated by Django 5.2.14 on 2026-05-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapps', '0005_responsecomment_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRAppDiscordSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_welcome_messages', models.BooleanField(default=False)),
                ('welcome_channel', models.BigIntegerField(blank=True, null=True)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('use_recruitment_threads', models.BooleanField(default=False)),
                ('recruitment_thread_channel', models.BigIntegerField(blank=True, null=True)),
                ('recruiter_role', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'HRApp Discord Settings',
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(('use_recruitment_threads', False), ('recruitment_thread_channel__isnull', False), _connector='OR'), name='recruitment_thread_channel_required_if_threads_enabled'), models.CheckConstraint(condition=models.Q(('enable_welcome_messages', False), ('welcome_channel__isnull', False), _connector='OR'), name='welcome_channel_required_if_welcome_messages_enabled')],
            },
        ),
    ]
