# Generated by Django 5.2.14 on 2026-06-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_userprofile_minimize_sidebar'),
        ('hrapps', '0006_hrappdiscordsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrappdiscordsettings',
            name='ignored_states',
            field=models.ManyToManyField(blank=True, to='authentication.state'),
        ),
    ]
