# Generated by Django 5.2.14 on 2026-06-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapps', '0007_hrappdiscordsettings_ignored_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrappdiscordsettings',
            name='recruit_role',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
