# Generated by Django 5.2.14 on 2026-07-10 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapps', '0008_hrappdiscordsettings_recruit_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='hrapps/attachments/')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hrapps.formresponse')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
