# Generated by Django 5.2.14 on 2026-07-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapps', '0009_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
