# Generated by Django 5.2.14 on 2026-08-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapps', '0010_attachment_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrappdiscordsettings',
            name='application_notification_channel',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrappdiscordsettings',
            name='enable_application_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
